version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map port 3000 on host to port 80 in container (Nginx for serving React)
    environment:
      - REACT_APP_API_URL=http://localhost:5000  # Backend URL for development
    networks:
      - app-network

networks:
  app-network:  # Ensure this network is defined here
    driver: bridge
